<?php

declare (strict_types=1);

namespace test;

use App\AtomicCalculator;
use Generator;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

class AtomicCalculatorTest extends TestCase
{
    #[DataProvider('provideElectronConfigurationCases')]
    public function testReturnsItProvidesElectronConfiguration(int $atomicNumber, string $expected): void
    {
        $electronConfigurationCalculator = new AtomicCalculator();

        $this->assertSame($expected, $electronConfigurationCalculator->calculateElectronConfiguration($atomicNumber));
    }

    /*
     * Provides electron configurations for first 54 elements (configurations generated by Claude)
     * Exceptions to Aufbau filling order are flagged below
     */
    public static function provideElectronConfigurationCases(): array
    {
        return [
            'Hydrogen (1)' => [1, '1s1'],
            'Helium (2)' => [2, '1s2'],
            'Lithium (3)' => [3, '1s2 2s1'],
            'Beryllium (4)' => [4, '1s2 2s2'],
            'Boron (5)' => [5, '1s2 2s2 2p1'],
            'Carbon (6)' => [6, '1s2 2s2 2p2'],
            'Nitrogen (7)' => [7, '1s2 2s2 2p3'],
            'Oxygen (8)' => [8, '1s2 2s2 2p4'],
            'Fluorine (9)' => [9, '1s2 2s2 2p5'],
            'Neon (10)' => [10, '1s2 2s2 2p6'],
            'Sodium (11)' => [11, '1s2 2s2 2p6 3s1'],
            'Magnesium (12)' => [12, '1s2 2s2 2p6 3s2'],
            'Aluminum (13)' => [13, '1s2 2s2 2p6 3s2 3p1'],
            'Silicon (14)' => [14, '1s2 2s2 2p6 3s2 3p2'],
            'Phosphorus (15)' => [15, '1s2 2s2 2p6 3s2 3p3'],
            'Sulfur (16)' => [16, '1s2 2s2 2p6 3s2 3p4'],
            'Chlorine (17)' => [17, '1s2 2s2 2p6 3s2 3p5'],
            'Argon (18)' => [18, '1s2 2s2 2p6 3s2 3p6'],
            'Potassium (19)' => [19, '1s2 2s2 2p6 3s2 3p6 4s1'],
            'Calcium (20)' => [20, '1s2 2s2 2p6 3s2 3p6 4s2'],
            'Scandium (21)' => [21, '1s2 2s2 2p6 3s2 3p6 3d1 4s2'],
            'Titanium (22)' => [22, '1s2 2s2 2p6 3s2 3p6 3d2 4s2'],
            'Vanadium (23)' => [23, '1s2 2s2 2p6 3s2 3p6 3d3 4s2'],
            'Chromium (24)' => [24, '1s2 2s2 2p6 3s2 3p6 3d5 4s1'], // Chromium (24): 3d5 4s1 instead of 3d4 4s2 (half-filled d subshell stability
            'Manganese (25)' => [25, '1s2 2s2 2p6 3s2 3p6 3d5 4s2'],
            'Iron (26)' => [26, '1s2 2s2 2p6 3s2 3p6 3d6 4s2'],
            'Cobalt (27)' => [27, '1s2 2s2 2p6 3s2 3p6 3d7 4s2'],
            'Nickel (28)' => [28, '1s2 2s2 2p6 3s2 3p6 3d8 4s2'],
            'Copper (29)' => [29, '1s2 2s2 2p6 3s2 3p6 3d10 4s1'], // Copper (29): 3d10 4s1 instead of 3d9 4s2 (fully-filled d subshell stability)
            'Zinc (30)' => [30, '1s2 2s2 2p6 3s2 3p6 3d10 4s2'],
            'Gallium (31)' => [31, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p1'],
            'Germanium (32)' => [32, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p2'],
            'Arsenic (33)' => [33, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p3'],
            'Selenium (34)' => [34, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p4'],
            'Bromine (35)' => [35, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p5'],
            'Krypton (36)' => [36, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6'],
            'Rubidium (37)' => [37, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s1'],
            'Strontium (38)' => [38, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s2'],
            'Yttrium (39)' => [39, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d1 5s2'],
            'Zirconium (40)' => [40, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d2 5s2'],
            'Niobium (41)' => [41, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d4 5s1'], // Niobium (41): 4d4 5s1
            'Molybdenum (42)' => [42, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s1'], // Molybdenum (42): 4d5 5s1 (half-filled d subshell stability)
            'Technetium (43)' => [43, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s2'],
            'Ruthenium (44)' => [44, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d7 5s1'], // Ruthenium (44): 4d7 5s1
            'Rhodium (45)' => [45, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d8 5s1'], // Rhodium (45): 4d8 5s1
            'Palladium (46)' => [46, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10'], // Palladium (46): 4d10 (no 5s electrons)
            'Silver (47)' => [47, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s1'], // Silver (47): 4d10 5s1 (fully-filled d subshell stability)
            'Cadmium (48)' => [48, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2'],
            'Indium (49)' => [49, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p1'],
            'Tin (50)' => [50, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p2'],
            'Antimony (51)' => [51, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p3'],
            'Tellurium (52)' => [52, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p4'],
            'Iodine (53)' => [53, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p5'],
            'Xenon (54)' => [54, '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6'],
        ];
    }
}